Fatal error: exception Failure("a exists in scope")
