Fatal error: exception Failure("x exists in scope")
